# Generated by Django 2.2.6 on 2019-10-22 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=11)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Nº pedido')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('conta', models.CharField(choices=[('NU', 'Nubank'), ('BB', 'Banco do Brasil'), ('SP', 'Safrapay'), ('MP', 'Mercado Pago'), ('JN', 'Jessianne'), ('JK', 'Jessica')], max_length=2)),
                ('data_pedido', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('pago', models.BooleanField(default=True, verbose_name='Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Cliente')),
            ],
            options={
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_Produto', models.CharField(choices=[('Fralda', 'Fralda'), ('Lenço', 'Lenço')], max_length=6)),
                ('marca_produto', models.CharField(choices=[('MamyPoko', 'MamyPoko'), ('Huggies', 'Huggies'), ('Pampers', 'Pampers'), ('Babysec', 'Babysec'), ('PomPom', 'PomPom'), ('Cremer', 'Cremer'), ('Looney Tunes', 'Looney Tunes'), ('Scooby-Doo', 'Scooby-Doo'), ('Hipopó', 'Hipopó'), ("Johnson's", "Johnson's")], max_length=12)),
                ('marca_modelo', models.CharField(max_length=50)),
                ('modelo_Produto', models.CharField(max_length=50)),
                ('unidades', models.PositiveIntegerField()),
                ('tamanho', models.CharField(choices=[('LN', 'Lenço'), ('RN', 'RN'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('XG', 'XG'), ('XXG', 'XXG'), ('GRA', 'Grandinhos')], max_length=3)),
                ('estoque', models.PositiveIntegerField()),
                ('valor_Entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_Saida', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='PedidoItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Mam', 'MamyPoko'), ('Hug', 'Huggies'), ('Pam', 'Pampers'), ('Bab', 'Babysec'), ('Pom', 'PomPom'), ('Cre', 'Cremer'), ('Loo', 'Looney Tunes'), ('Sco', 'Scooby-Doo'), ('Hip', 'Hipopó'), ('Joh', "Johnson's")], max_length=3)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produtos')),
            ],
            options={
                'verbose_name_plural': 'itens',
            },
        ),
    ]
